Prevent vote spoofing
Prop-House/prop-house-monorepo pull request #284
Opened 2022-10-19 15:46 UTC by cryptoseneca

Currently, a valid signature and a matching `CreateVoteDTO` was enough to bypass checks and allow attacker to use any address to vote on any proposal. 

This PR adds a check to make sure that the proposal being voted on (`foundProposal`) matches the community address of the signed vote.

2022-10-23 17:46 UTC, gitblamecarrot requested changes
This appears to only validate the first vote in the payload that matches the proposal ID. Shouldn't it be something along the lines of `all(checkVote, votes.filter(v => v.proposalID === proposal.id))`?

2022-10-25 13:41 UTC, cryptoseneca commented
> This appears to only validate the first vote in the payload that matches the proposal ID. Shouldn't it be something along the lines of `all(checkVote, votes.filter(v => v.proposalID === proposal.id))`?

That's correct. While the payload does bring multiple votes, only the vote for the `dto.proposalId` is being casted. That is, for each vote in the payload, the wrapper shoots a `POST` call. So what we're doing is really verifying that the corresponding vote is valid.

2022-10-25 15:13 UTC, gitblamecarrot commented
Ah, ok thought it was POSTing a batch. Whenever I see `.find()` I just get nervous. Will go with what you think 👍

2022-10-25 15:13 UTC, gitblamecarrot approved these changes

2022-10-27 17:03 UTC, merged