New Proposal Modal
Prop-House/prop-house-monorepo pull request #299
Opened 2022-10-26 20:27 UTC by cdt-eth

2022-11-18 16:03 UTC, cryptoseneca requested changes
Great job all around, the modal is a great UX improvement. Some UX stuff I noticed:

- “tldr” and “description” titles should have diff font color to differentiate from actual prop content 
- “More” button when prop modal content is long is very hard to read - let’s add shadow (or something) to make it stand out more

on design side: 
- let's add "connect to vote" on prop modal if in round_voting state && not connected

other:
- I noticed a few components that made it to the `pages` directory that should not be there, let's move those [1]


[1]
<img width="337" alt="Screen Shot 2022-11-18 at 11 02 25 AM" src="https://user-images.githubusercontent.com/85328329/202748344-27d5ce63-f7ff-4413-aa1a-81abc3dd9a61.png">

2022-11-18 17:31 UTC, cdt-eth commented
> * I noticed a few components that made it to the `pages` directory that should not be there, let's move those [1]

addressed https://github.com/Prop-House/prop-house-monorepo/pull/299/commits/d81751c82a709d2bdf3d254f6121e83b840c19bf

2022-11-18 17:37 UTC, cdt-eth commented on packages/prop-house-webapp/src/components/ProposalFooter/index.tsx
> +const ProposalFooter: React.FC<{
https://github.com/Prop-House/prop-house-monorepo/pull/299/commits/98db1a496f4bd411c2f9766995aafc10a3b80c7c

2022-11-18 19:51 UTC, cdt-eth commented on packages/prop-house-webapp/src/components/ProposalFooter/index.tsx
> +  round: StoredAuction;
https://github.com/Prop-House/prop-house-monorepo/pull/299/commits/c6cfca1cbbaec6564c45a3b23524e3b57cdfd870

2022-11-18 19:53 UTC, cdt-eth commented on packages/prop-house-webapp/src/components/ProposalModal/index.tsx
> +              proposal={proposal}
https://github.com/Prop-House/prop-house-monorepo/pull/299/commits/c6cfca1cbbaec6564c45a3b23524e3b57cdfd870

2022-11-18 19:53 UTC, cdt-eth commented on packages/prop-house-webapp/src/components/ProposalModal/index.tsx
> +            <ProposalFooter
https://github.com/Prop-House/prop-house-monorepo/pull/299/commits/c6cfca1cbbaec6564c45a3b23524e3b57cdfd870

2022-11-18 19:58 UTC, cdt-eth commented on packages/prop-house-webapp/src/components/VoteConfirmationModal/index.tsx
> +          Cast {voteAllotments.reduce((total, prop) => (total = total + prop.votes), 0)}{' '}
https://github.com/Prop-House/prop-house-monorepo/pull/299/commits/3fb6adb26511cba31d51391497dbb18513ade0ac

2022-11-18 20:04 UTC, cdt-eth commented on packages/prop-house-webapp/src/components/ProposalModal/index.tsx
> +            <ProposalHeaderAndBody
So we already do, @cryptoseneca. The `ProposalHeader` is [here](https://github.com/Prop-House/prop-house-monorepo/blob/3fb6adb26511cba31d51391497dbb18513ade0ac/packages/prop-house-webapp/src/components/ProposalHeaderAndBody/ProposalHeaderAndBody.tsx#L77-L91) and the body is the `ProposalContent` component, [on line 106](https://github.com/Prop-House/prop-house-monorepo/blob/3fb6adb26511cba31d51391497dbb18513ade0ac/packages/prop-house-webapp/src/components/ProposalHeaderAndBody/ProposalHeaderAndBody.tsx#L106), which is used in several other places in the codebase. 

The entire `ProposalBodyAndHeader` component is to encompass all the overflow scrolling logic & UI and keep it out of its parent, `ProposalModal`, which is already busy enough.

2022-11-18 20:09 UTC, cdt-eth commented on packages/prop-house-webapp/src/components/ProposalModal/index.tsx
> +    if (!community || !round) return;
https://github.com/Prop-House/prop-house-monorepo/pull/299/commits/b1074d6841b9d24a21048a9569f395733e077400

2022-11-18 20:12 UTC, cdt-eth commented on packages/prop-house-webapp/src/components/ProposalHeader/index.tsx
> +const ProposalHeader: React.FC<ProposalHeaderProps> = props => {
https://github.com/Prop-House/prop-house-monorepo/pull/299/commits/d05a26f3b6bf841b3417565d7e2378f5ea95aa1a

2022-11-18 21:05 UTC, cdt-eth commented on packages/prop-house-webapp/src/components/ProposalModal/index.tsx
> +  useEffect(() => {
https://github.com/Prop-House/prop-house-monorepo/pull/299/commits/cc47939dcbdbadd70cc962f9e7230063a2311859

2022-12-01 18:23 UTC, cryptoseneca commented
Some UX issues I found during testing via desktop: 

- [1] during round ended, weird space below “more”, let’s remove.
- [2] during proposing / voting state, connect to submit prop should be centered
- [3] if you go into a round, click a prop, close the modal and click the back button (to go to the house page), the prop modal will open again
- [4] Use capital letter “No votes allotted”
- [5] once the allotment modal is opened, there’s no way to close it while staying on the same prop



[1]
<img width="1187" alt="Screen Shot 2022-12-01 at 12 36 06 PM" src="https://user-images.githubusercontent.com/85328329/205130706-50a88552-7b4f-4c4f-b368-a2e9c7ba081e.png">
[2]
<img width="1263" alt="Screen Shot 2022-12-01 at 12 42 15 PM" src="https://user-images.githubusercontent.com/85328329/205130727-b9df12cc-54ca-495a-9330-914c407b755a.png">

[3]
<img width="856" alt="Jun 1, 2022 - Jun 8, 2023" src="https://user-images.githubusercontent.com/85328329/205130749-c75a45b3-8c22-4b94-bf10-c055f2713e65.png">

[4]
<img width="202" alt="no votes allotted" src="https://user-images.githubusercontent.com/85328329/205130772-32bb7a11-22c2-4bd7-a122-7b0039173d49.png">

[5]
<img width="581" alt="have to de" src="https://user-images.githubusercontent.com/85328329/205130789-75e398d1-f9d1-45da-be3d-f5d0ab76208b.png">

2022-12-01 22:00 UTC, cdt-eth commented
### [1] during round ended, weird space below “more”, let’s remove.

### [2] during proposing / voting state, connect to submit prop should be centered
fixed: https://github.com/Prop-House/prop-house-monorepo/pull/299/commits/cc4cebb835c070bcfa14fad47235e3cda81f6854
<img width="1194" alt="Screenshot 2022-12-01 at 4 58 50 PM" src="https://user-images.githubusercontent.com/26611339/205167787-ee2d7abd-1a38-47b8-870b-5b7747f84c60.png">

### [3] if you go into a round, click a prop, close the modal and click the back button (to go to the house page), the prop modal will open again

###[4] Use capital letter “No votes allotted”
https://github.com/Prop-House/prop-house-monorepo/pull/299/commits/cc4cebb835c070bcfa14fad47235e3cda81f6854

### [5] once the allotment modal is opened, there’s no way to close it while staying on the same prop
it closes both on scroll and after clicking the icon again. can you try again? i've verified this on my end.

2022-12-23 00:01 UTC, merged